drone1:
  ekf:
    ros__parameters:
      ref_lat: 48.04630
      ref_lon: -4.97632
      ref_alt: 0.0
      process_noise: 0.01
      gps_noise: 2.0
      gps_noise_xy: 10.0
      gps_noise_z: 10.0
      process_noise_v: 0.02
      process_noise_bias_x: 1e-3
      process_noise_bias_y: 1e-3
      
            
drone2:
  ekf:
    ros__parameters:
      ref_lat: 48.04630
      ref_lon: -4.97632
      ref_alt: 0.0
      process_noise: 0.01
      gps_noise: 2.0
      gps_noise_xy: 10.0
      gps_noise_z: 10.0
      process_noise_v: 0.02
      process_noise_bias_x: 1e-3
      process_noise_bias_y: 1e-3
      
            
drone3:
  ekf:
    ros__parameters:
      ref_lat: 48.04630
      ref_lon: -4.97632
      ref_alt: 0.0
      process_noise: 0.01
      gps_noise: 2.0
      gps_noise_xy: 10.0
      gps_noise_z: 10.0
      process_noise_v: 0.02
      process_noise_bias_x: 1e-3
      process_noise_bias_y: 1e-3      
