ekf_node:
  ros__parameters:
    q_pos: 0.05
    q_vel: 0.02
    r_gps: 3.0
    r_gps_x: 1.0
    r_gps_y: 10.0
    r_gps_z: 100.0
    initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    utm_origin_easting: 352704.20
    utm_origin_northing: 5323335.38
    utm_origin_altitude: 1.20
    gps_x_offset: 0.0
    gps_y_offset: 0.0
